version: 0.2

phases:
  build:
    commands:
    - echo "This is build phase... Zipping my lambda function"
    - zip -r lambda_function.zip lambda_function.py
  post_build:
    commands:
    - echo "Deploying to the Lambda"
    - aws lambda update-function-code --function-name  Hello_world --zip-file fileb://lambda_function.zip
artifacts:
  type: zip
  paths:
    - '*'
